### ISSUE TITLE
how to achieve the acc in the paper?

### ISSUE THREAD

**Issue by 1024AILab** [PKU-ICST-MIPL/DCR-ReID_TCSVT2023#4]
![image](https://github.com/PKU-ICST-MIPL/DCR-ReID_TCSVT2023/assets/39455680/b7d027ea-1721-4d04-82e8-cdeb3e64067d)
I train the code for many times, they all can't get the Rank1 at 57.1, how to solve that ?

**Comment by hxy-499** [comment]
Did you solve that?

**Comment by hxy-499** [comment]
> ![image](https://user-images.githubusercontent.com/39455680/273438319-b7d027ea-1721-4d04-82e8-cdeb3e64067d.png) I train the code for many times, they all can't get the Rank1 at 57.1, how to solve that ?

Did you solve that?
